use burn::module::Module;
use burn::record::{BinBytesRecorder, HalfPrecisionSettings, Recorder};
use burn::tensor::backend::BackendTypes;
// Only one of the Linear/ResNet families is actually referenced below, chosen by
// whichever `network_type` export_web generated into net_config.rs.
#[allow(unused_imports)]
use mz_core::config::{
    GPoolConfig, HeadPoolConfig, LinearSubConfig, NetConfig, NetworkSubConfig, NetworkType,
    ProjectionSubConfig, ResNetBlockConfig, ResNetRepresentationConfig, ResNetSubConfig,
};
use mz_core::networks::MuZeroNets;

use crate::search::SearchParams;

// Generated by `cargo run -r --bin export_web` next to the weights, so the
// module shapes, network family, and search constants can never drift from
// configs/config.yaml.
include!("../assets/net_config.rs");

static WEIGHTS: &[u8] = include_bytes!("../assets/othello.bin");

#[cfg(feature = "flex")]
pub type Be = burn::backend::Flex;
#[cfg(all(feature = "ndarray", not(feature = "flex")))]
pub type Be = burn::backend::NdArray;

pub type Device = <Be as BackendTypes>::Device;

pub async fn init_backend(_device: &Device) {}

pub fn load(device: &Device) -> Net<Be> {
    let record = BinBytesRecorder::<HalfPrecisionSettings, &'static [u8]>::default()
        .load(WEIGHTS, device)
        .expect("the embedded Othello weights should match NET");
    Net::init(&NET, device).load_record(record)
}
