//! ChessMamba: a searchless policy+value net trained in the separate
//! bee-chess repo (`training/src/bee_training/chess_mamba/`), unlike this
//! crate's Othello/Chess agents -- no representation/dynamics networks, no
//! latent-space MCTS. `chess_mamba_bot.rs` calls `forward` once per move and
//! argmaxes the (from, to) policy logits over the position's legal moves; see
//! that module for why (`gumbel_search` needs a `MuZeroNets` impl this
//! doesn't have).
//!
//! Generated by `build.rs` from `onnx/chess_mamba.onnx` -- edit that onnx
//! file (re-export it from bee-chess) to change the network, not this file.
#![allow(clippy::all, unused_imports, unused_variables)]
extern crate alloc;

include!(concat!(env!("OUT_DIR"), "/chess_mamba/chess_mamba.rs"));
