[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[patch.crates-io]
ale = { git = "https://github.com/BrageHK/ale-rs", rev = "6f9b68fca8be9e21c98b305b4abcbcff5f1d00af" }
ale-sys = { git = "https://github.com/BrageHK/ale-rs", rev = "6f9b68fca8be9e21c98b305b4abcbcff5f1d00af" }

[workspace.dependencies]
burn = { version = "~0.21", default-features = false }
burn-import = { version = "~0.21", features = ["onnx"] }
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.10.1"
rand_distr = "0.6.0"
